// MLBB Heroes Database Schema
// Heroes collection - user can add images manually

const heroes = [
  // Tank Heroes
  { id: "tank_001", name: "Tanksworth", role: "Tank", specialties: ["Initiator", "Crowd Control"], damage_type: "Melee", region: "Global" },
  { id: "tank_002", name: "Grock", role: "Tank", specialties: ["Wall", "Defense"], damage_type: "Melee", region: "Global" },
  { id: "tank_003", name: "Hylos", role: "Tank", specialties: ["Mana Regen", "Zone Control"], damage_type: "Melee", region: "Global" },
  { id: "tank_004", name: "Johnson", role: "Tank", specialties: ["Charge", "CC"], damage_type: "Melee", region: "Global" },
  { id: "tank_005", name: "Minotour", role: "Tank", specialties: ["AOE CC", "Initiation"], damage_type: "Melee", region: "Global" },
  { id: "tank_006", name: "Thamuz", role: "Tank", specialties: ["Sustain", "Damage"], damage_type: "Melee", region: "Global" },
  { id: "tank_007", name: "Fredrinn", role: "Tank", specialties: ["Burst", "Shield"], damage_type: "Melee", region: "Global" },
  { id: "tank_008", name: "Chip", role: "Tank", specialties: ["Pet", "Summon"], damage_type: "Melee", region: "Global" },
  { id: "tank_009", name: "Barats", role: "Tank", specialties: ["Mini", "Pet Control"], damage_type: "Melee", region: "Global" },
  { id: "tank_010", name: "Lolita", role: "Tank", specialties: ["Nuke", "Protection"], damage_type: "Melee", region: "Global" },

  // Fighter Heroes
  { id: "fighter_001", name: "Balmond", role: "Fighter", specialties: ["Lifesteal", "AOE"], damage_type: "Melee", region: "Global" },
  { id: "fighter_002", name: "Alucard", role: "Fighter", specialties: ["Lifesteal", "Finisher"], damage_type: "Melee", region: "Global" },
  { id: "fighter_003", name: "Zilong", role: "Fighter", specialties: ["Split Push", "Finisher"], damage_type: "Melee", region: "Global" },
  { id: "fighter_004", name: "Freya", role: "Fighter", specialties: ["Burst", "Mobility"], damage_type: "Melee", region: "Global" },
  { id: "fighter_005", name: "Chou", role: "Fighter", specialties: ["Dodge", "CC"], damage_type: "Melee", region: "Global" },
  { id: "fighter_006", name: "Jawhead", role: "Fighter", specialties: ["Turret Dive", "Burst"], damage_type: "Melee", region: "Global" },
  { id: "fighter_007", name: "Leomord", role: "Fighter", specialties: ["Mount", "AOE"], damage_type: "Melee", region: "Global" },
  { id: "fighter_008", name: "Yyu", role: "Fighter", specialties: ["Energy", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "fighter_009", name: "Arteria", role: "Fighter", specialties: ["Charge", "Zone Control"], damage_type: "Melee", region: "Global" },
  { id: "fighter_010", name: "Julian", role: "Fighter", specialties: ["Hybrid", "Burst"], damage_type: "Melee", region: "Global" },
  { id: "fighter_011", name: "Hilda", role: "Fighter", specialties: ["Regen", "Ambush"], damage_type: "Melee", region: "Global" },
  { id: "fighter_012", name: "Amber", role: "Fighter", specialties: ["Mage-Fighter", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "fighter_013", name: "Masha", role: "Fighter", specialties: ["Bear Form", "Duel"], damage_type: "Melee", region: "Global" },
  { id: "fighter_014", name: "Python", role: "Fighter", specialties: ["Pet", "Execute"], damage_type: "Melee", region: "Global" },
  { id: "fighter_015", name: "Camille", role: "Fighter", specialties: ["Hook", "Trade"], damage_type: "Melee", region: "Global" },
  { id: "fighter_016", name: "Fanny", role: "Fighter", specialties: ["Cable", "Snowball"], damage_type: "Physical", region: "Global" },
  { id: "fighter_017", name: "Hayabusa", role: "Fighter", specialties: ["Clone", "Assassin"], damage_type: "Melee", region: "Global" },
  { id: "fighter_018", name: "K措施", role: "Fighter", specialties: ["Counter", "Durable"], damage_type: "Melee", region: "Global" },
  { id: "fighter_019", name: "Baxia", role: "Fighter", specialties: ["Shield", "Engage"], damage_type: "Melee", region: "Global" },
  { id: "fighter_020", name: "Edward", role: "Fighter", specialties: ["Dash", "Finisher"], damage_type: "Melee", region: "Global" },
  { id: "fighter_021", name: "X.Borg", role: "Fighter", specialties: ["Armor", "Burn"], damage_type: "Melee", region: "Global" },
  { id: "fighter_022", name: "Lapu", role: "Fighter", specialties: ["Sword", "Immunity"], damage_type: "Melee", region: "Global" },
  { id: "fighter_023", name: "Dyrroth", role: "Fighter", specialties: ["Burst", "Mobility"], damage_type: "Melee", region: "Global" },
  { id: "fighter_024", name: "Minsi", role: "Fighter", specialties: ["Berserk", "Execute"], damage_type: "Melee", region: "Global" },
  { id: "fighter_025", name: "Ryze", role: "Fighter", specialties: ["Mobility", "Poke"], damage_type: "Melee", region: "Global" },

  // Assassin Heroes
  { id: "assassin_001", name: "Saber", role: "Assassin", specialties: ["Burst", "Finisher"], damage_type: "Physical", region: "Global" },
  { id: "assassin_002", name: "Fanny", role: "Assassin", specialties: ["Cable", "Snowball"], damage_type: "Physical", region: "Global" },
  { id: "assassin_003", name: "Hayabusa", role: "Assassin", specialties: ["Clone", "Assassin"], damage_type: "Physical", region: "Global" },
  { id: "assassin_004", name: "Natalia", role: "Assassin", specialties: ["Stealth", "Ambush"], damage_type: "Physical", region: "Global" },
  { id: "assassin_005", name: "Ling", role: "Assassin", specialties: ["Climb", "Finisher"], damage_type: "Physical", region: "Global" },
  { id: "assassin_006", name: "Joy", role: "Assassin", specialties: ["Mobility", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "assassin_007", name: "Aamon", role: "Assassin", specialties: ["Decoy", "Burst"], damage_type: "Physical", region: "Global" },
  { id: "assassin_008", name: "Selena", role: "Assassin", specialties: ["Abyss", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "assassin_009", name: "Gusion", role: "Assassin", specialties: ["Combo", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "assassin_010", name: "Harith", role: "Assassin", specialties: ["Mobility", "poke"], damage_type: "Magic", region: "Global" },
  { id: "assassin_011", name: "Lancelot", role: "Assassin", specialties: ["Dodge", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "assassin_012", name: "Kimmy", role: "Assassin", specialties: ["Hybrid", "Poke"], damage_type: "Hybrid", region: "Global" },
  { id: "assassin_013", name: "Y Eve", role: "Assassin", specialties: ["Crowd Control", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "assassin_014", name: "Kamanga", role: "Assassin", specialties: ["Charge", "Knockback"], damage_type: "Melee", region: "Global" },
  { id: "assassin_015", name: "Hanzo", role: "Assassin", specialties: ["Ninja", "Burst"], damage_type: "Physical", region: "Global" },
  { id: "assassin_016", name: "Kazumi", role: "Assassin", specialties: ["Pet", "Ranged"], damage_type: "Magic", region: "Global" },

  // Mage Heroes
  { id: "mage_001", name: "Cyclops", role: "Mage", specialties: ["Nuke", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "mage_002", name: "Eudora", role: "Mage", specialties: ["Stun", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "mage_003", name: "Bruno", role: "Mage", specialties: ["Crit", "Mobility"], damage_type: "Physical", region: "Global" },
  { id: "mage_004", name: "Liliana", role: "Mage", specialties: ["Transform", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "mage_005", name: "Chang'e", role: "Mage", specialties: ["Moon", "Sustain"], damage_type: "Magic", region: "Global" },
  { id: "mage_006", name: "Vale", role: "Mage", specialties: ["Burst", "AOE"], damage_type: "Magic", region: "Global" },
  { id: "mage_007", name: "Zhuxin", role: "Mage", specialties: ["Support", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "mage_008", name: "Xavier", role: "Mage", specialties: ["Suppress", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "mage_009", name: "Lunox", role: "Mage", specialties: ["Light/Dark", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "mage_010", name: "Esmeralda", role: "Mage", specialties: ["Shield", "Sustain"], damage_type: "Magic", region: "Global" },
  { id: "mage_011", name: "Faramier", role: "Mage", specialties: ["Petrify", "Zone Control"], damage_type: "Magic", region: "Global" },
  { id: "mage_012", name: "Neco", role: "Mage", specialties: ["Cat", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "mage_013", name: "Novaria", role: "Mage", specialties: ["Astral", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "mage_014", name: "Yve", role: "Mage", specialties: ["CC", "Zone Control"], damage_type: "Magic", region: "Global" },
  { id: "mage_015", name: " Luo Yi", role: "Mage", specialties: ["Teleport", "AOE"], damage_type: "Magic", region: "Global" },
  { id: "mage_016", name: "Pharsa", role: "Mage", specialties: ["Bird", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "mage_017", name: "Valir", role: "Mage", specialties: ["Burst", "Push"], damage_type: "Magic", region: "Global" },
  { id: "mage_018", name: " Gord", role: "Mage", specialties: ["Turret", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "mage_019", name: "Aurora", role: "Mage", specialties: ["Freeze", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "mage_020", name: "Mea", role: "Mage", specialties: ["Puppet", "CC"], damage_type: "Magic", region: "Global" },
  { id: "mage_021", name: "Rachel", role: "Mage", specialties: ["Angel", "Buff"], damage_type: "Magic", region: "Global" },
  { id: "mage_022", name: "Harley", role: "Mage", specialties: ["Duel", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "mage_023", name: "Odette", role: "Mage", specialties: ["Swan", "Heal"], damage_type: "Magic", region: "Global" },
  { id: "mage_024", name: "Alice", role: "Mage", specialties: ["Mobility", "Regen"], damage_type: "Magic", region: "Global" },
  { id: "mage_025", name: "Kagura", role: "Mage", specialties: ["UMB", "Burst"], damage_type: "Magic", region: "Global" },
  { id: "mage_026", name: "Violet", role: "Mage", specialties: ["Locked", "Burst"], damage_type: "Physical", region: "Global" },
  { id: "mage_027", name: "Lynn", role: "Mage", specialties: ["Charge", "CC"], damage_type: "Magic", region: "Global" },
  { id: "mage_028", name: "Zhang Ling", role: "Mage", specialties: ["Energy", "Nuke"], damage_type: "Magic", region: "Global" },
  { id: "mage_029", name: "申叔", role: "Mage", specialties: ["Shield", "Poke"], damage_type: "Magic", region: "Global" },
  { id: "mage_030", name: "Melissa", role: "Mage", specialties: ["Love", "Burst"], damage_type: "Magic", region: "Global" },

  // Marksman Heroes
  { id: "marksman_001", name: "Miya", role: "Marksman", specialties: ["Crit", "Farming"], damage_type: "Physical", region: "Global" },
  { id: "marksman_002", name: "Layla", role: "Marksman", specialties: ["Sniper", "Late Game"], damage_type: "Physical", region: "Global" },
  { id: "marksman_003", name: "Karrie", role: "Marksman", specialties: ["True Damage", "Lategame"], damage_type: "Physical", region: "Global" },
  { id: "marksman_004", name: "Clint", role: "Marksman", specialties: ["Poke", "Trap"], damage_type: "Physical", region: "Global" },
  { id: "marksman_005", name: "Moskov", role: "Marksman", specialties: ["Spear", "Punish"], damage_type: "Physical", region: "Global" },
  { id: "marksman_006", name: "Yi Sun-shin", role: "Marksman", specialties: ["Crit", "Global Ult"], damage_type: "Physical", region: "Global" },
  { id: "marksman_007", name: "Beatrix", role: "Marksman", specialties: ["Weapons", "Adaptable"], damage_type: "Physical", region: "Global" },
  { id: "marksman_008", name: "Natan", role: "Marksman", specialties: ["Crit", "Lifesteal"], damage_type: "Physical", region: "Global" },
  { id: "marksman_009", name: "Popol", role: "Marksman", specialties: ["Kupa", "Pet"], damage_type: "Physical", region: "Global" },
  { id: "marksman_010", name: "Brody", role: "Marksman", specialties: ["Line", "Fish"], damage_type: "Physical", region: "Global" },
  { id: "marksman_011", name: "Ixpan", role: "Marksman", specialties: ["Trap", "Zone"], damage_type: "Physical", region: "Global" },
  { id: "marksman_012", name: "Ralph", role: "Marksman", specialties: ["Dash", "Finisher"], damage_type: "Physical", region: "Global" },
  { id: "marksman_013", name: "Cobb", role: "Marksman", specialties: ["Speed", "Crit"], damage_type: "Physical", region: "Global" },
  { id: "marksman_014", name: "皮皮", role: "Marksman", specialties: ["Mascot", "Poke"], damage_type: "Physical", region: "Global" },
  { id: "marksman_015", name: "狩猎", role: "Marksman", specialties: ["Hunter", "Snipe"], damage_type: "Physical", region: "Global" },
  { id: "marksman_016", name: "Kelphy", role: "Marksman", specialties: ["Petal", "Zone Control"], damage_type: "Magic", region: "Global" },
  { id: "marksman_017", name: "Roger", role: "Marksman", specialties: ["Wolf", "Hybrid"], damage_type: "Physical", region: "Global" },
  { id: "marksman_018", name: "Hasis", role: "Marksman", specialties: ["Rocket", "AOE"], damage_type: "Physical", region: "Global" },
  { id: "marksman_019", name: "Brelo", role: "Marksman", specialties: ["Energy", "Sustain"], damage_type: "Physical", region: "Global" },
  { id: "marksman_020", name: "Jam", role: "Marksman", specialties: ["Music", "Slow"], damage_type: "Magic", region: "Global" },

  // Support Heroes
  { id: "support_001", name: "Angela", role: "Support", specialties: ["Puppet", "Heal"], damage_type: "Magic", region: "Global" },
  { id: "support_002", name: "Estes", role: "Support", specialties: ["Heal", "Immortal"], damage_type: "Magic", region: "Global" },
  { id: "support_003", name: "Mathilda", role: "Support", specialties: ["Dive", "Shield"], damage_type: "Magic", region: "Global" },
  { id: "support_004", name: "Rafaela", role: "Support", specialties: ["Heal", "True Sight"], damage_type: "Magic", region: "Global" },
  { id: "support_005", name: "Floryn", role: "Support", specialties: ["Flower", "Debuff"], damage_type: "Magic", region: "Global" },
  { id: "support_006", name: "Pearl", role: "Support", specialties: ["Shell", "Shield"], damage_type: "Magic", region: "Global" },
  { id: "support_007", name: "Saline", role: "Support", specialties: ["Titan", "Buff"], damage_type: "Magic", region: "Global" },
  { id: "support_008", name: "Chip", role: "Support", specialties: ["Candy", "Pet"], damage_type: "Magic", region: "Global" },
  { id: "support_009", name: "Mitchell", role: "Support", specialties: ["Sonic", "Speed"], damage_type: "Magic", region: "Global" },
  { id: "support_010", name: "Lilian", role: "Support", specialties: ["Rose", "Love"], damage_type: "Magic", region: "Global" },

  // Mage/Support Hybrids
  { id: "hybrid_001", name: "Diggie", role: "Support", specialties: ["Nest", "Anti-Initiator"], damage_type: "Magic", region: "Global" },
  { id: "hybrid_002", name: "Rotunda", role: "Support", specialties: ["Orb", "Zone Control"], damage_type: "Magic", region: "Global" },
  { id: "hybrid_003", name: "Carmilla", role: "Support", specialties: ["Revenge", "Execute"], damage_type: "Magic", region: "Global" },
  { id: "hybrid_004", name: "Terizla", role: "Support", specialties: ["Shield", "Damage"], damage_type: "Melee", region: "Global" }
];

module.exports = heroes;